name: "azuright"
branding:
  icon: "hard-drive"
  color: "blue"
description: "Installs azurite (Azure storage emulator) on Windows, macOS or Linux."
inputs:
  install:
    description: "The apps to install"
    required: true
  sa-password:
    description: "The sa password for the SQL instance"
    required: false
    default: "dbatools.I0"
  show-log:
    description: "Show the log file for the docker container"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - id: psoutput
      shell: pwsh
      env:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: ${{ inputs.sa-password }}
        MSSQL_AGENT_ENABLED: "true"
        HOMEBREW_NO_ENV_FILTERING: "1"
      run: |
        Write-Output "Getting variables for suite"

        $params = @{
            Install         = ("${{ inputs.install }}" -split ",").Trim()
            ShowLog         = $${{ inputs.show-log }}
        }

        ./main.ps1 @params
